// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyeJaCtsQ2U-jlf_hhJO7d7Qq5XgGEEXM',
    appId: '1:1045036222251:web:0f9f44ee5e8ee0b9dce76e',
    messagingSenderId: '1045036222251',
    projectId: 'evently-app-f8c0b',
    authDomain: 'evently-app-f8c0b.firebaseapp.com',
    storageBucket: 'evently-app-f8c0b.firebasestorage.app',
    measurementId: 'G-BN9X9FPFV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXe0XkQTc7dnVd7By75w3mfx2rt5ekAVI',
    appId: '1:1045036222251:android:2e62d38c7ea3edfcdce76e',
    messagingSenderId: '1045036222251',
    projectId: 'evently-app-f8c0b',
    storageBucket: 'evently-app-f8c0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUA9LLZbQCQwqCJ4DY1xd6AawhbIg_Fu0',
    appId: '1:1045036222251:ios:ff5fa01efcbbe630dce76e',
    messagingSenderId: '1045036222251',
    projectId: 'evently-app-f8c0b',
    storageBucket: 'evently-app-f8c0b.firebasestorage.app',
    iosBundleId: 'com.example.myeventlyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUA9LLZbQCQwqCJ4DY1xd6AawhbIg_Fu0',
    appId: '1:1045036222251:ios:ff5fa01efcbbe630dce76e',
    messagingSenderId: '1045036222251',
    projectId: 'evently-app-f8c0b',
    storageBucket: 'evently-app-f8c0b.firebasestorage.app',
    iosBundleId: 'com.example.myeventlyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyeJaCtsQ2U-jlf_hhJO7d7Qq5XgGEEXM',
    appId: '1:1045036222251:web:7a70c71b8aa00981dce76e',
    messagingSenderId: '1045036222251',
    projectId: 'evently-app-f8c0b',
    authDomain: 'evently-app-f8c0b.firebaseapp.com',
    storageBucket: 'evently-app-f8c0b.firebasestorage.app',
    measurementId: 'G-NP5ZEFGZL5',
  );
}
